pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "vedant573"
        IMAGE_NAME = "ats-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE = "${DOCKERHUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --break-system-packages -r app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                python -m pytest app/tests
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $FULL_IMAGE -f docker/Dockerfile .
                '''
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerHubCred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $FULL_IMAGE
                    '''
                }
            }
        }
	stage('Update GitOps Repo') {
    	    steps {
        	sh '''
        	git clone https://github.com/Vedant573/ats-gitops.git
        	cd ats-gitops
        	sed -i "s/REPLACEME/${IMAGE_TAG}/g" k8s/ats/deployment.yaml
        	git config user.email "jenkins@local"
        	git config user.name "jenkins"
        	git add .
        	git commit -m "Deploy ATS image ${IMAGE_TAG}"
        	git push origin main
        	'''
   	     }
	}

    }
}

